### ISSUE TITLE
Fix display on new Versa 3 and Sense squircle faces

### ISSUE THREAD

**Issue by BaronVonPerko** [BaronVonPerko/fitbit-roni#16]
Currently needs enabling from within package.json

**Comment by BaronVonPerko** [comment]
OS 5.0 will not be released to older devices (Versa,Versa2,Ionic).  Therefore, we will need to make two separate projects.  Many resources should be shared between the two projects to make development of these two separate watchfaces easier.

**Comment by RichardUmney1** [comment]
I've tidied up the sizing of all the shapes.  Cannot get the steps and calorie images to move left far enough.

Also added comma's into the steps number (struggling with the calories) for when they tip over 1,000.
Added a new date format, and tidied up the spacing on the others.

**Comment by BaronVonPerko** [comment]
Awesome work.  I'm happy to take a look at a PR when you're ready @RichardUmney1 👍
