### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by fadookie** [BaronVonPerko/fitbit-roni#6]
I just noticed after opening https://github.com/BaronVonPerko/fitbit-roni/pull/5 that you don't actually have a LICENSE in the repo so I am not sure what requirements I need to follow in order to publish my fork.

I'd have a look through https://choosealicense.com/ to find one that fits your idea of how this project can be used. I usually go with MIT if I don't care what people do with the code or GPLv3 if I want to ensure that modifications are required to be released under the original license terms.

**Comment by BaronVonPerko** [comment]
Yes, I'm going to go with MIT, just never bothered to put it on the repository.  I'll definitely be sure to do it.  Do whatever you please with the code, and thanks for letting me know!

**Comment by fadookie** [comment]
Awesome, thank you!
